In [1]:
# Import depndencies 
import pandas as pd 
import numpy as np
from sqlalchemy import create_engine
from config import dbConnectionString

In [2]:
# Create SQLEngine -- use "pip install psycopg2-binary" if ModuleError occurs
engine = create_engine(dbConnectionString)

In [3]:
#load in data from sql database
Cardiovas_df = pd.read_sql_query('Select * FROM "USChronicDiseaseIndicatorsCDI" WHERE "Topic" like %(cvd)s',
            con=engine,
            params={"cvd":'Cardiovascular Disease'})

In [4]:
Cardiovas_df.head()

,index,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,...,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,36490,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Hospitalization for heart failure among Medica...,None,None,...,54,CVD,CVD2_0,NMBR,GENDER,GENF,None,None,None,None
1,31975,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Hospitalization for heart failure among Medica...,None,None,...,44,CVD,CVD2_0,NMBR,RACE,BLK,None,None,None,None
2,40686,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Hospitalization for heart failure among Medica...,None,None,...,31,CVD,CVD2_0,NMBR,OVERALL,OVR,None,None,None,None
3,41479,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Hospitalization for heart failure among Medica...,None,None,...,20,CVD,CVD2_0,NMBR,RACE,HIS,None,None,None,None
4,41835,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Hospitalization for heart failure among Medica...,None,None,...,48,CVD,CVD2_0,NMBR,RACE,HIS,None,None,None,None

In [5]:
#drop unnecessary columns
Cardiovas_df.drop(columns = ['index','Question','Response','DataValueUnit','DataValueFootnoteSymbol','DatavalueFootnote','StratificationCategory2','Stratification2','StratificationCategory3','Stratification3','StratificationCategoryID2','StratificationID2','StratificationCategoryID3','StratificationID3'],
            axis=1, inplace=True)
Cardiovas_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,DataValueAlt,LowConfidenceLimit,...,StratificationCategory1,Stratification1,GeoLocation,ResponseID,LocationID,TopicID,QuestionID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,3060.0,NaN,...,Gender,Female,POINT (-80.71264013 38.6655102),None,54,CVD,CVD2_0,NMBR,GENDER,GENF
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,113.0,NaN,...,Race/Ethnicity,"Black, non-Hispanic",POINT (-71.52247031 41.70828019),None,44,CVD,CVD2_0,NMBR,RACE,BLK
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,2734.0,NaN,...,Overall,Overall,POINT (-99.36572062 41.64104099),None,31,CVD,CVD2_0,NMBR,OVERALL,OVR
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,32.0,NaN,...,Race/Ethnicity,Hispanic,POINT (-98.20078123 38.3477403),None,20,CVD,CVD2_0,NMBR,RACE,HIS
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,2181.0,NaN,...,Race/Ethnicity,Hispanic,POINT (-99.42677021 31.82724041),None,48,CVD,CVD2_0,NMBR,RACE,HIS

In [7]:
# drop the LocatioAbbr , DataValueAlt  column to make the date more clean
Cardiovas_df.drop('DataValueAlt', axis=1, inplace=True)

In [8]:
#number of NaN values

Cardiovas_df["ResponseID"].isna().sum()

128676

In [9]:
# drop the QuestionID column to make the date more clean
Cardiovas_df.drop('QuestionID', axis=1, inplace=True)
# drop ResponseID  because all the values are NaN
Cardiovas_df.drop("ResponseID", axis=1 ,inplace=True)

In [10]:
Cardiovas_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,NaN,NaN,Gender,Female,POINT (-80.71264013 38.6655102),54,CVD,NMBR,GENDER,GENF
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,NaN,NaN,Race/Ethnicity,"Black, non-Hispanic",POINT (-71.52247031 41.70828019),44,CVD,NMBR,RACE,BLK
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,NaN,NaN,Overall,Overall,POINT (-99.36572062 41.64104099),31,CVD,NMBR,OVERALL,OVR
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,NaN,NaN,Race/Ethnicity,Hispanic,POINT (-98.20078123 38.3477403),20,CVD,NMBR,RACE,HIS
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,NaN,NaN,Race/Ethnicity,Hispanic,POINT (-99.42677021 31.82724041),48,CVD,NMBR,RACE,HIS

In [11]:
# Replace Nan values with zeroes to make it easier for machine learning
#this dataset was eventually not used for ML 
Cardiovas_df['LocationDesc']=Cardiovas_df['LocationDesc'].fillna(0)
Cardiovas_df['DataSource']=Cardiovas_df['DataSource'].fillna(0)
Cardiovas_df['StratificationCategory1']=Cardiovas_df['StratificationCategory1'].fillna(0)
Cardiovas_df['Stratification1']=Cardiovas_df['Stratification1'].fillna(0)
Cardiovas_df['LocationID']=Cardiovas_df['LocationID'].fillna(0)
Cardiovas_df['TopicID']=Cardiovas_df['TopicID'].fillna(0)
Cardiovas_df['DataValueTypeID']=Cardiovas_df['DataValueTypeID'].fillna(0)
Cardiovas_df['DataValueTypeID']=Cardiovas_df['DataValueTypeID'].fillna(0)
Cardiovas_df['StratificationCategoryID1']=Cardiovas_df['StratificationCategoryID1'].fillna(0)
Cardiovas_df['StratificationID1']=Cardiovas_df['StratificationID1'].fillna(0)
Cardiovas_df['DataValue']=Cardiovas_df['DataValue'].fillna(0)
Cardiovas_df['LowConfidenceLimit']=Cardiovas_df['LowConfidenceLimit'].fillna(0)
Cardiovas_df['HighConfidenceLimit']=Cardiovas_df['HighConfidenceLimit'].fillna(0)

In [12]:
Cardiovas_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,0.0,0.0,Gender,Female,POINT (-80.71264013 38.6655102),54,CVD,NMBR,GENDER,GENF
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,0.0,0.0,Race/Ethnicity,"Black, non-Hispanic",POINT (-71.52247031 41.70828019),44,CVD,NMBR,RACE,BLK
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,0.0,0.0,Overall,Overall,POINT (-99.36572062 41.64104099),31,CVD,NMBR,OVERALL,OVR
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,0.0,0.0,Race/Ethnicity,Hispanic,POINT (-98.20078123 38.3477403),20,CVD,NMBR,RACE,HIS
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,0.0,0.0,Race/Ethnicity,Hispanic,POINT (-99.42677021 31.82724041),48,CVD,NMBR,RACE,HIS

In [13]:
 # .str.replace to understand the structure of the column which parts will be removed  
    
Cardiovas_df['GeoLocation'].str.replace(r"([POINT])", r" \1").str.split(expand=True)

/Users/CLaw/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

        0  1  2  3  4              5             6
0       P  O  I  N  T  (-80.71264013   38.6655102)
1       P  O  I  N  T  (-71.52247031  41.70828019)
2       P  O  I  N  T  (-99.36572062  41.64104099)
3       P  O  I  N  T  (-98.20078123   38.3477403)
4       P  O  I  N  T  (-99.42677021  31.82724041)
...    .. .. .. .. ..            ...           ...
128671  P  O  I  N  T  (-81.92896054  28.93204038)
128672  P  O  I  N  T  (-92.56630005  38.63579078)
128673  P  O  I  N  T  (-111.5871306  39.36070017)
128674  P  O  I  N  T  (-72.51764079  43.62538124)
128675  P  O  I  N  T  (-108.1098304  43.23554134)

[128676 rows x 7 columns]

In [14]:
# Removing POINT and the parentheses () from the column
Cardiovas_df['GeoLocation'] = Cardiovas_df['GeoLocation'].str.replace('[POINT]', '')
Cardiovas_df['GeoLocation'] = Cardiovas_df['GeoLocation'].str.replace('[()]', '')

/Users/CLaw/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

/Users/CLaw/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until

In [15]:
temp_df = Cardiovas_df
temp_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,DataValueTypeID,StratificationCategoryID1,StratificationID1
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,0.0,0.0,Gender,Female,-80.71264013 38.6655102,54,CVD,NMBR,GENDER,GENF
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,0.0,0.0,Race/Ethnicity,"Black, non-Hispanic",-71.52247031 41.70828019,44,CVD,NMBR,RACE,BLK
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,0.0,0.0,Overall,Overall,-99.36572062 41.64104099,31,CVD,NMBR,OVERALL,OVR
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,0.0,0.0,Race/Ethnicity,Hispanic,-98.20078123 38.3477403,20,CVD,NMBR,RACE,HIS
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,0.0,0.0,Race/Ethnicity,Hispanic,-99.42677021 31.82724041,48,CVD,NMBR,RACE,HIS

In [16]:
Cardiovas_df[['longitude','latitude']] = Cardiovas_df['GeoLocation'].str.lstrip().str.rstrip().str.split(' ',1,expand=True)

In [17]:
Cardiovas_df[Cardiovas_df['longitude'].isna()]
Cardiovas_df.dropna(subset=['longitude','latitude'],axis=0, inplace=True)

In [18]:
Cardiovas_df[["longitude", "latitude"]] = Cardiovas_df[["longitude", "latitude"]].apply(pd.to_numeric)

In [19]:
Cardiovas_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,DataValueTypeID,StratificationCategoryID1,StratificationID1,longitude,latitude
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,0.0,0.0,Gender,Female,-80.71264013 38.6655102,54,CVD,NMBR,GENDER,GENF,-80.712640,38.665510
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,0.0,0.0,Race/Ethnicity,"Black, non-Hispanic",-71.52247031 41.70828019,44,CVD,NMBR,RACE,BLK,-71.522470,41.708280
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,0.0,0.0,Overall,Overall,-99.36572062 41.64104099,31,CVD,NMBR,OVERALL,OVR,-99.365721,41.641041
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,0.0,0.0,Race/Ethnicity,Hispanic,-98.20078123 38.3477403,20,CVD,NMBR,RACE,HIS,-98.200781,38.347740
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,0.0,0.0,Race/Ethnicity,Hispanic,-99.42677021 31.82724041,48,CVD,NMBR,RACE,HIS,-99.426770,31.827240

In [20]:
Cardiovas_df.dtypes

YearStart                      int64
YearEnd                        int64
LocationAbbr                  object
LocationDesc                  object
DataSource                    object
Topic                         object
DataValueType                 object
DataValue                     object
LowConfidenceLimit           float64
HighConfidenceLimit          float64
StratificationCategory1       object
Stratification1               object
GeoLocation                   object
LocationID                     int64
TopicID                       object
DataValueTypeID               object
StratificationCategoryID1     object
StratificationID1             object
longitude                    float64
latitude                     float64
dtype: object

In [21]:
Cardiovas_df['GeoLocation']

0           -80.71264013 38.6655102
1          -71.52247031 41.70828019
2          -99.36572062 41.64104099
3           -98.20078123 38.3477403
4          -99.42677021 31.82724041
                    ...
128671     -81.92896054 28.93204038
128672     -92.56630005 38.63579078
128673     -111.5871306 39.36070017
128674     -72.51764079 43.62538124
128675     -108.1098304 43.23554134
Name: GeoLocation, Length: 127962, dtype: object

In [22]:
Cardiovas_df.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,DataValueType,DataValue,LowConfidenceLimit,HighConfidenceLimit,StratificationCategory1,Stratification1,GeoLocation,LocationID,TopicID,DataValueTypeID,StratificationCategoryID1,StratificationID1,longitude,latitude
0,2016,2016,WV,West Virginia,CMS Part A Claims Data,Cardiovascular Disease,Number,3060.0,0.0,0.0,Gender,Female,-80.71264013 38.6655102,54,CVD,NMBR,GENDER,GENF,-80.712640,38.665510
1,2017,2017,RI,Rhode Island,CMS Part A Claims Data,Cardiovascular Disease,Number,113.0,0.0,0.0,Race/Ethnicity,"Black, non-Hispanic",-71.52247031 41.70828019,44,CVD,NMBR,RACE,BLK,-71.522470,41.708280
2,2016,2016,NE,Nebraska,CMS Part A Claims Data,Cardiovascular Disease,Number,2734.0,0.0,0.0,Overall,Overall,-99.36572062 41.64104099,31,CVD,NMBR,OVERALL,OVR,-99.365721,41.641041
3,2015,2015,KS,Kansas,CMS Part A Claims Data,Cardiovascular Disease,Number,32.0,0.0,0.0,Race/Ethnicity,Hispanic,-98.20078123 38.3477403,20,CVD,NMBR,RACE,HIS,-98.200781,38.347740
4,2014,2014,TX,Texas,CMS Part A Claims Data,Cardiovascular Disease,Number,2181.0,0.0,0.0,Race/Ethnicity,Hispanic,-99.42677021 31.82724041,48,CVD,NMBR,RACE,HIS,-99.426770,31.827240

In [23]:
#Cardiovas_df.to_csv(r'Resources\CleanedUsa.csv', index = False)
Cardiovas_df.to_sql('cvdus',engine, if_exists="replace")